applications/departamento/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name="departamento_app"

urlpatterns = [
    path('admin/', admin.site.urls),
    path(
        'departamento/lista/',
        views.DepartamentoListView.as_view(), 
        name='departamento-list'),
    path(
        'new-departamento/', 
        views.NewDepartamentoView.as_view(), 
        name='nuevo_departamento'
        ),
]

urls.py
from django.urls import path
from .import views 

app_name="persona_app"

urlpatterns = [
      
    path(
        '', 
         views.InicioView.as_view(),
         name='inicio'
         ),

    path(
        'listar-todos-empleados/',
         views.LisAllEmpleados.as_view(),
         name='empleados_all'),

    path('list-by-area/<subnombre>/',
        views.ListByAreaEmpleado.as_view(),
        name='empleados_area'),

    path('lista-empleados-admin/',
        views.ListaEmpleadosAdmin.as_view(),
        name='empleados_admin'),
        

    path('buscar-empleado/', views.ListEmpleadoBykword.as_view()),
    path('lista-habilidades-empleado/', views.ListHabilidadesEmplado.as_view()),
    path(
        'ver-empleado/<pk>/', 
        views.EmpleadoDetailView.as_view(),
        name='empleado_detail'
        ),
    path('add-empleado/', 
         views.EmpleadoCreateView.as_view(),
         name='empleados_add'),

    path('success/',
          views.SuccessView.as_view(), 
          name='correcto'
          ),
     path('update-empleado/<pk>/',
          views.EmpleadoUdateView.as_view(), 
          name='modificar_empleado'
          ),
    path('delete-empleado/<pk>/',
          views.EmpleadoDeleteView.as_view(), 
          name='eliminar_empleado'
          ),
]

templates/include/header.html
<div class="top-bar">
  <div class="top-bar-left">
    <ul class="dropdown menu" data-dropdown-menu>
      <li class="menu-text">Empleados</li>

      <li>
        <a href="{% url 'persona_app:empleados_all' %}">Listar</a>
      </li>

      <li>
        <a href="{% url 'departamento_app:departamento-list' %}">Departamento</a>
      </li>

      <li>
        <a href="{% url 'persona_app:empleados_admin' %}">Administrar</a>
      </li>
    </ul>
  </div>

  <div class="top-bar-right">
    <ul class="menu">
      <li><input type="search" placeholder="Buscar Empleado"></li>
      <li>
        <a href="{% url 'persona_app:empleado_add' %}">Registrar Nuevo</a>
      </li>
    </ul>
  </div>
</div>